### ISSUE TITLE
mmtc crashes when playlist file contains an url

### ISSUE THREAD

**Issue by cooljith91112** [figsoda/mmtc#167]
If I have a `playlist` file which includes an audio(mp3) file with a `http(s)` URL, When I open `mmtc`, it crashes with the following error
```
Failed to disable mouse capture

Caused by:
    Initial console modes not set
```
I have tested with mpc and it is playing fine

OS: Windows 10
mmtc Version : 0.3.0

**Comment by figsoda** [comment]
Can you try if the current master works?

**Comment by cooljith91112** [comment]
> Can you try if the current master works?

Yes, it's working, and I was able to play from a URL. 
![image](https://user-images.githubusercontent.com/2651484/205601299-d28a2019-1aeb-44c5-a58c-67b7be0100e8.png)

But I don't know this is supported or not but mmtc doesn't show m3u playlist data (I have a m3u file which I populated with `#EXTINF` and mp3 URL - standard m3u format).

sample m3u
```
#EXTM3U

#EXTINF:279, Jasper Byrne – Decade Dance
https://retrowave.ru//audio/d37ee09b5293270ad415c26054421f1ac8d83fa1.mp3

```

![image](https://user-images.githubusercontent.com/2651484/205601976-c206a498-32b8-4fb4-b4c7-62ccf3a740cf.png)

**Comment by figsoda** [comment]
I am not sure how to fix that since I am getting information from mpd, but playing the music once was able to fix the issue for me

**Comment by cooljith91112** [comment]
> I am not sure how to fix that since I am getting information from mpd, but playing the music once was able to fix the issue for me

Yes, you are right. Current changes in master does fixes the crash.

**Comment by figsoda** [comment]
I found out the cause of this and the current master should show the url now

**Comment by figsoda** [comment]
0.3.1 has been published
